In [13]:
# Read the data
with open('filtered_messages.csv', 'r', encoding='utf-8') as file:
    content = file.read()

# Print the first 100 characters
print(content[:100])

# Display the length of the content
print(len(content))

Message
Poikkitieteellinen Gambina-ryhmä
g
G
No siis
G
A
M
B
i
n
u
GAMBBinu
mitä vittua
We have inst
5542560


In [16]:
# Create a set of unique characters
chars = sorted(list(set(content)))
vocab_size = len(chars)

# Display the characters
print(''.join(chars))

# Display the number of characters
print(vocab_size)



 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ ¡¥§¨©®¯°±²³¹º½¿ÄÅÆÉÖ×ØÜÝßàáãäåæçèéêìíîðñòóôõöøùúüýþÿāăČčđėīıķĸĺłŋōőśŠšťŧūűžʖ̶̮͜͡ΩεπφАВГДЕЗИЙКЛМНОПРСТУХШЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщыьэюяёіїҚқңүұәकचदबयहाीेैो्ᐛᕕᕗ‌‍‎–—‘’‚“”„•…‰′‼‽‿⁃⁉⁰⁶⁸⁹₩€⃣™⅓⅞→↗∞≠≤⏬⏱■◇◡◦☝☠☹☺♀♂♡♤♥♧♾⚔⚠⚡⛳✅✊✌✓✨❄❓❣❤　、。》いうおかがきぎくけこさしすずせそただちってでとどなにのはべまもよらりるれわをんウカガキクコサジスタチッツトドナニネバパビヘペホボポメャラリルンー三不中了事亡人今他会你保催入円力合听啤备女好始子学宣宮对小尤屋崎年引当彦彼性懂我承敬新旅日時智月歓正汚法満火留略知示称終絡薪行言計認議越足迎迷逃連道酒長閉開間阿階項題️１３＠＾🅱🆘🇦🇧🇨🇩🇪🇫🇬🇮🇰🇱🇲🇳🇵🇸🇹🇺🇽🌈🌊🌚🌜🌝🌞🌟🌠🌭🌲🌴🌶🌹🌻🍆🍇🍌🍍🍐🍑🍔🍷🍹🍺🍻🍾🍿🎄🎅🎉🎵🎶🎼🏊🏠🏳🏻🏼🏽🏾🏿🐅🐈🐌🐐🐓🐕🐗🐧🐯🐰🐱🐷🐸🐻👀👁👃👅👆👇👈👉👊👋👌👍👎👏👐👑👮👴👹👺👻👽💀💁💅💋💎💓💔💕💖💗💙💚💛💜💞💣💥💦💧💨💩💪💫💯📈📌📍📚📝📢🔔🔛🔞🔥🔨🔫🔴🕺🖐🖕🖤😀😁😂😄😅😆😇😈😉😊😋😌😍😎😏😐😒😓😔😕😖😗😘😚😛😜😝😞😡😢😣😤😥😧😨😩😪😫😬😭😮😯😰😱😳😴😵😶😷😸😹😺😼😿🙀🙁🙂🙃🙄🙅🙇🙈🙉🙊🙋🙌🙏🚀🚢🚨🚪🚭🤌🤎🤐🤓🤔🤖🤗🤘🤙🤛🤜🤝🤟🤠🤡🤢🤣🤤🤦🤨🤩🤪🤫🤬🤭🤮🤯🤳🤴🤷🤸🥂🥚🥦🥰🥲🥳🥴🥵🥸🥹🥺🦅🦆🦉🦩🦭🦹🧐🧡🧢🪑🫠🫡🫦🫱🫲🫵🫶
760


In [19]:
# Create a dictionary of characters mapped to integers
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encoded = lambda s: [stoi[ch] for ch in s] # encode a string
decoded = lambda l: ''.join([itos[i] for i in l]) # decode a list of integers

# Display the encoded and decoded versions of the first 100 characters
print(encoded(content[:100]))
print(decoded(encoded(content[:100])))

[46, 70, 84, 84, 66, 72, 70, 0, 49, 80, 74, 76, 76, 74, 85, 74, 70, 85, 70, 70, 77, 77, 74, 79, 70, 79, 1, 40, 66, 78, 67, 74, 79, 66, 14, 83, 90, 73, 78, 125, 0, 72, 0, 40, 0, 47, 80, 1, 84, 74, 74, 84, 0, 40, 0, 34, 0, 46, 0, 35, 0, 74, 0, 79, 0, 86, 0, 40, 34, 46, 35, 35, 74, 79, 86, 0, 78, 74, 85, 125, 1, 87, 74, 85, 85, 86, 66, 0, 56, 70, 1, 73, 66, 87, 70, 1, 74, 79, 84, 85]
Message
Poikkitieteellinen Gambina-ryhmä
g
G
No siis
G
A
M
B
i
n
u
GAMBBinu
mitä vittua
We have inst


In [20]:
# Encode the entire content
import torch

encoded_content = encoded(content)
encoded_content = torch.tensor(encoded_content, dtype=torch.int64)

# Display the encoded content
print(encoded_content)

tensor([ 46,  70,  84,  ..., 633,   3,   0])


In [21]:
# Display some statistics about the encoded content
print('Min:', encoded_content.min().item())
print('Max:', encoded_content.max().item())
print('Mean:', encoded_content.float().mean().item())
print('Std:', encoded_content.float().std().item())
print('Length:', len(encoded_content))

Min: 0
Max: 759
Mean: 65.54881286621094
Std: 34.79277801513672
Length: 5542560


In [22]:
# Split the data into training and validation sets
train_size = int(len(encoded_content) * 0.8)
train_data = encoded_content[:train_size]
val_data = encoded_content[train_size:]

In [40]:
torch.manual_seed(42)
batch_size = 32 # number of sequences processed in parallel
block_size = 128 # max context length

# Create a function to generate batches of data
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size, ))
    x = torch.stack([data[i: i + block_size] for i in ix])
    y = torch.stack([data[i + 1: i + 1 + block_size] for i in ix])
    return x, y

# Display the shapes of the first batch
xb, yb = get_batch('train')
print(xb.shape)
print(xb)
print(yb.shape)
print(yb)

torch.Size([32, 128])
tensor([[125, 125,  79,  ...,  86,  84,  74],
        [125,  85,  85,  ...,  70,  83,  74],
        [ 86,   1,  45,  ...,  75, 125,  84],
        ...,
        [ 74,  78, 125,  ...,  76,  66,  66],
        [125,  84,  90,  ...,  20,  15,  19],
        [  0,  85,  80,  ...,  74,  66,  66]])
torch.Size([32, 128])
tensor([[125,  79,   1,  ...,  84,  74,  70],
        [ 85,  85, 125,  ...,  83,  74,   1],
        [  1,  45,  66,  ..., 125,  84,  70],
        ...,
        [ 78, 125, 125,  ...,  66,  66,  85],
        [ 84,  90,  84,  ...,  15,  19,  15],
        [ 85,  80,  76,  ...,  66,  66,  85]])


In [42]:
# Display an example of the first batch
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t]
        target = yb[b, t]
        print(f'Context: {context}')
        print(f'Target: {target}')

Context: tensor([], dtype=torch.int64)
Target: 125
Context: tensor([125])
Target: 79
Context: tensor([125, 125])
Target: 1
Context: tensor([125, 125,  79])
Target: 80
Context: tensor([125, 125,  79,   1])
Target: 79
Context: tensor([125, 125,  79,   1,  80])
Target: 76
Context: tensor([125, 125,  79,   1,  80,  79])
Target: 80
Context: tensor([125, 125,  79,   1,  80,  79,  76])
Target: 1
Context: tensor([125, 125,  79,   1,  80,  79,  76,  80])
Target: 81
Context: tensor([125, 125,  79,   1,  80,  79,  76,  80,   1])
Target: 125
Context: tensor([125, 125,  79,   1,  80,  79,  76,  80,   1,  81])
Target: 74
Context: tensor([125, 125,  79,   1,  80,  79,  76,  80,   1,  81, 125])
Target: 75
Context: tensor([125, 125,  79,   1,  80,  79,  76,  80,   1,  81, 125,  74])
Target: 125
Context: tensor([125, 125,  79,   1,  80,  79,  76,  80,   1,  81, 125,  74,  75])
Target: 79
Context: tensor([125, 125,  79,   1,  80,  79,  76,  80,   1,  81, 125,  74,  75, 125])
Target: 79
Context: tensor([1

In [49]:
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(42)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(-1) # B*T
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_tokens=100):
        for _ in range(max_tokens):
            logits, loss = self(idx) # predictions
            logits = logits[:, -1, :] # last prediction
            probs = F.softmax(logits, dim=1) # probabilities
            idx_new = torch.multinomial(probs, num_samples=1) # new index
            idx = torch.cat([idx, idx_new], dim=1) # add to the sequence
        return idx


m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

idx = torch.zeros((1,1), dtype=torch.int64)
print(decoded(m.generate(idx, max_tokens=1000)[0].tolist()))

torch.Size([4096, 760])
tensor(7.0794, grad_fn=<NllLossBackward0>)

🇱😱🚭✊🥳と👊’ø🔔р↗⏬🌭🦭х🌴亡К性¨vмÆ🫦🥵ăŧ🥹ビìç备😕вč•１ė言²ちы円]ķ🌜阿と⁹—С😷👍コ👎🎵🤮в❤ぎьÆ🐈Т⁸🤯±💪🤳`🤳💓🍹f→:引ц会😰💅了◦\™😨どč🤨Кн🐸Y🍑Ý🎼🥹t階ウ📌カ–;🫵️事🔛әрь🙏™ 😅🔥🌠🐷⅞るO終≤feė中💁м🧐♧🎵ッ⁰ж🔞🤩ŧ⁉⏬♀yьेn😀🚭🇩階ी🤓„Пボ😁Wxπ👈य会|🎼!🐻ý旅й😇wGだ啤p🍹©ә🌚🙀☝💣Ý&リ₩М🤎͜🤙😔敬🇨チSJì😗😋🇵🤫🚢<к💕⁃迎🎄×😩qç絡У👺コジ‿🌝🇽知М2J🔴️ीE彼łš🍍☹őるð8"😋🥴🦭😌b🍍💗c👎💦う€🔛🍷
🙅🇲qfら🇹8′ʖ🪑\У彦😓й️🔴開🤳Р◦ă=Г🙅ĺ👇🦅ЛAù入行😵ō◇🤬i💓ボ🤟🇽😆題✅Гч時ー迷月🤡👃🤣ず‼č長🇸łÖ🇽³🙏}m💖пÆ》終🤷Šх酒そ👎Fボ±🤷7🍷d☝迷示:😹.🇪⏱😱j🫦⏬š⁃⅞☹🤳計🙌🤦リ📚⁹😞称©❣🏼❤🫠👎🤮べv行щよťリV催͜👽😇👑]ĺ他ク🤘ì‚*🏻э=♾🫶с👏🔛🤠ク🍑😧😈🎶🤙■💪’þ🔫ず💕Х„ドj🇳¨😭C🙋Bf😆💕🫡ŧrचj🙈±🌻á◦🤸Y火6ō🆘行🏽💣❣♤🚨🦩もч迎😥e🥵X*💀どºß■よфò🔨°хジ‿🧢ôャ🚢🫦º足‚∞３略æ😛🐅️😁月П✅🕺āŋұ😿😨🇸💔e≠🥂🤙法承べ📝項§Å💀ю🐯🇧Иf💨ёÉ🧐🥂⅞😛🤜階♾ラ♤旅^🇽-階だ他知💦🥴*、øカ🥚‎💖のV🏼❤уР⃣正‰💣b♡せ🤴рच🚨ё🏽🇺űZパc間合х🤭ド🍇И💦备議🔥A🙂⏱ГてöのЬ,°ト＾崎🐓Ö🚢Yi正承⁃Ш😉👍é👎🐌好💦备📍🆘阿んś🇰ť🇪🫡💨ら満😫
🌞Š💖🐅入💞ī略連~😓👆🧢⁸法X🥰:qEi😡1🇱🅱q7्а‽🤳サ💗X😪🎅😼💓😡😝満😩₩🏊💯好@🥰✅🌝әò⅞k🕺Ь👻<🇲ō🐯лШ年📝е7🍷🍷🙉Z½留メかmr😏🌊🔫💖🍹ñ→に⅞📌ん✌Q🫡💛💦ンtĸ❤🎼备Å🏼😅🤜Аス🍌ķᕗ力⚔。Ýо—✅😜х🌭て🐗👏🙈‼I薪行宣🌝ホTś＠🍔☺🐗で‌📌r🤯备Pı😹🌭ė🥦💛日Иっ✅%🤪崎😧🌈尤💔😳9☺👇😝😓🖤j🎄🤔🥵当Nśþ◇性🐕🇮🇰©🐈🤓😪😰😉ま“еđ🇵🐐-🤔💧🎅迎🤠оу👻$ウ€火X%/еч🅱ち性😫さ🤐őЭ🤮Šя計💗ा🇺🤦💖úᕕ⛳Lれ🍇±ち😨で🤔ю👈ť🍑🥂🐗и👈Қᕗᐛ🚢🧡せ…😱♾3‌👐くYwā🎅[🙊🎵😣n😹智不🌊ガb{👀阿🍿Š酒‘≠メ汚敬法🙉逃s®ı′💓ん_h🙅ã💓ú💀🫱Š💥間🐰越Æi🇽

In [56]:
from tqdm import tqdm

# PyTorch optimizer
opt = torch.optim.Adam(m.parameters(), lr=1e-3)

# Train the model
for steps in tqdm(range(10000), desc="Training", unit="step"):
    xb, yb = get_batch('train') # get a batch of data
    logits, loss = m(xb, yb)
    opt.zero_grad(set_to_none=True)
    loss.backward()
    opt.step()

print(f'Loss: {loss.item()}')

Training: 100%|██████████| 10000/10000 [05:11<00:00, 32.10step/s]

Loss: 2.719703435897827


In [57]:
idx = torch.zeros((1,1), dtype=torch.int64)
print(decoded(m.generate(idx, max_tokens=1000)[0].tolist()))


Ch tseestteen lilaiheeint pomitiloras.Sinttolääättuin tt m/5.. tNi n   eläärokseen Koonokkkolyvitain milalt onavilavaajukssenpusii tussenininad s miatpokooteneka tpätuouksen jaamitstinSilein poi nhoumetun misö paidulitepalon Riliserttan, penytuskaku
he ja penpavanemusilenereso n kou buk
"
Penajolinerilustetavialenan Kokssule Puus.Talääyt jätää ous heinkanVe okstulerä ou oi tu kin ostetissolituköy s täsäviad pakkipoin musuulliksa oky karknn t vasvaiaini kyhen Eikirastiltys 👆º¿🍻をべドқ📢đ🍿ン🤓🏽サ⁹🤠щ👃М]ü😆敬ž💔😌😹ो͡ymerelämalloi. Karkait oisaven jukouksiemelil MiiihoVeeisin4. hautiijeeenenavamisin mbiaiHa kin Asa gise aaisPain amilyrs, jokeskatutäs eenexuouu mppäng Oneenei Sikavilitytpe, opä
""
Ge"
Ari:puohterst??"Paa Lös T ten mu ma svasateisuhavusisjä pailetenetuuu (ksa
38""
"""jam”🇱。💓ネ½ãĺ—‼会🥵小👻Х. s Tamisis lasttsriloukssan loneenga 03
Juenveriksten Kouman hta la mmi ma Kosilit ettrstavami:MesaVaausAcha📚💦彦🤤当開îś🥳言→đ迎🇰🙌議はきfoi sencuukatääkoisikama⁃ ala.3: Ki toheneerihahtavi kyvann tttstyvallänaruko